import fs from "node:fs/promises";
import { FileBlob, SpreadsheetFile } from "file:///C:/Users/noxis/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@oai/artifact-tool/dist/artifact_tool.mjs";
const root = "D:/GameDev/ProjectDG";
const path = root + "/outputs/balance_xlsx_20260717/DefenseGame_Balance_Skill_Summary.xlsx";
const workbook = await SpreadsheetFile.importXlsx(await FileBlob.load(path));
const sheet = workbook.worksheets.getItem("Validation_2026-07-17");
sheet.getRange("E1:E12").format.columnWidth = 24;
sheet.getRange("F1:F12").format.columnWidth = 38;
sheet.getRange("A10:F12").format.rowHeight = 62;
const preview = await workbook.render({ sheetName: "Validation_2026-07-17", autoCrop: "all", scale: 0.8, format: "png" });
await fs.writeFile(root + "/TempXlsxPreviewAfter/validation_final.png", new Uint8Array(await preview.arrayBuffer()));
const errors = await workbook.inspect({ kind: "match", searchTerm: "#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A", options: { useRegex: true, maxResults: 300 }, maxChars: 30000 });
const output = await SpreadsheetFile.exportXlsx(workbook);
await output.save(path);
console.log(JSON.stringify({ formulaErrors: errors.ndjson }));
